# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Learn
    url: /#features
    weight: 20
    hasChildren: true
  - parent: Learn
    name: All resources
    url: learn
  - parent: Learn
    name: Publications
    url: publications
  - name: Data
    url: data
    weight: 30
  - name: Software
    url: software
    weight: 40
  - name: Playground
    url: playground
    weight: 50
  - name: About
    url: /#about
    weight: 60