# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: indigo
  font: native # options: native, minimal, rose, cyberpunk [tech looking], 'Mr Robot', classic
  font_size: s

# SEO
marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: 'PIMLXplore'
    description: 'Explore Physics-informed Machine Learning - project funded by NSF.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: ''
    baidu: ''

# Site features
features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - python
      - julia
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/nxtruong/PIMLXplore-Website'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: "PIMLXplore"
      # Logo filename in `assets/media/` folder
      # filename: "logo.svg"
    # button:
    #   enable: false
    #   text: "Get Started"
    #   url: "https://hugoblox.com/templates/"
    # show_search: true
    # show_day_night: true
    show_theme_chooser: true

# Extensions
extensions:
  academicons:
    enable: true

# Citation style

publications:
  date_format: January 2006
  citation_style: apa

# Site footer
footer:
  copyright:
    notice: '© {year} iCPS Lab, University of Central Florida. All rights reserved.'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us
